Release 1.3.0
ondewo/ondewo-s2t-client-python pull request #1
Opened 2021-02-22 14:45 UTC by rinjac

2021-02-22 16:21 UTC, andrey999333 approved these changes

2021-02-23 12:58 UTC, AzzerAce commented on examples/file_transcription_example.py
> +    parser.add_argument("--config", type=str)
can we add descriptions to these arguments?

2021-02-23 13:04 UTC, AzzerAce requested changes
can we also add the secure_grpc.json example with placeholder values and the comment i added?
otherwise looks ok

2021-02-24 10:13 UTC, AzzerAce commented on examples/file_transcription_example.py
> +    parser.add_argument("--config", type=str, help="The GRPC configuration file. "
```suggestion
    parser.add_argument("--config", type=str, help="The GRPC configuration file path. "
```

2021-02-24 10:15 UTC, AzzerAce requested changes
minor change

2021-02-24 10:16 UTC, AzzerAce approved these changes

2021-02-24 10:16 UTC, merged